# Generated by Django 2.2 on 2020-11-29 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compras', '0001_initial'),
        ('articulos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='id_remision',
            field=models.ForeignKey(db_column='id_remision', on_delete=django.db.models.deletion.CASCADE, to='compras.NotaRemision'),
        ),
    ]
