# Generated by Django 2.2 on 2020-12-06 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0002_inventario_id_remision'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventario',
            name='id_remision',
        ),
        migrations.AddField(
            model_name='inventario',
            name='costo_promedio',
            field=models.FloatField(default=None),
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('tipo', models.BooleanField()),
                ('costo', models.FloatField(default=None)),
                ('fecha', models.DateField(default=None)),
                ('id_inventario', models.ForeignKey(db_column='id_inventario', on_delete=django.db.models.deletion.CASCADE, to='articulos.Inventario')),
            ],
            options={
                'verbose_name': 'Movimiento',
                'verbose_name_plural': 'Movimiento',
                'db_table': 'Movimiento',
                'default_permissions': [],
            },
        ),
    ]
