# Generated by Django 2.2 on 2020-12-06 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0002_inventario_id_remision'),
    ]

    operations = [
        migrations.RenameField(
            model_name='oferta',
            old_name='id_articulos',
            new_name='id_articulo',
        ),
    ]
