# Generated by Django 2.2 on 2020-12-06 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0003_auto_20201206_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
    ]
