# Generated by Django 2.2 on 2020-12-09 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0003_auto_20201205_2121'),
        ('articulos', '0005_auto_20201208_2230'),
    ]

    operations = [
    ]
