# Generated by Django 2.2 on 2020-11-30 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articulos', '0001_initial'),
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequesionCompra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_pedido', models.IntegerField()),
                ('fecha_pedido', models.DateField()),
                ('fecha_entrega', models.DateField()),
                ('estado', models.CharField(max_length=30)),
                ('id_articulo', models.ManyToManyField(to='articulos.Articulo')),
                ('id_departamento', models.ForeignKey(db_column='id_departamento', on_delete=django.db.models.deletion.CASCADE, to='personas.Departamento')),
            ],
            options={
                'verbose_name': 'Requsicion',
                'verbose_name_plural': 'Requisicion',
                'db_table': 'Requisicion',
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='ordenCompra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_total', models.FloatField()),
                ('fecha_orden', models.DateField()),
                ('fecha_entrega', models.DateField()),
                ('id_oferta', models.ForeignKey(db_column='id_oferta', on_delete=django.db.models.deletion.CASCADE, to='articulos.OfertaArticulo')),
                ('id_requisicion', models.ForeignKey(db_column='id_requisicion', on_delete=django.db.models.deletion.CASCADE, to='compras.RequesionCompra')),
            ],
            options={
                'verbose_name': 'orden de compra',
                'verbose_name_plural': 'ordenes de compra',
                'db_table': 'orden de compra',
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='NotaRemision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_total', models.FloatField()),
                ('id_orden', models.ForeignKey(db_column='id_orden', on_delete=django.db.models.deletion.CASCADE, to='compras.ordenCompra')),
                ('id_proveedor', models.ForeignKey(db_column='id_proveedor', on_delete=django.db.models.deletion.CASCADE, to='personas.EmpresaProvedora')),
            ],
            options={
                'verbose_name': 'Nota remision',
                'verbose_name_plural': 'Notas remision',
                'db_table': 'Nota remision',
                'default_permissions': [],
            },
        ),
    ]
