# Generated by Django 2.2 on 2020-12-06 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requesioncompra',
            name='comprahecha',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
