# Generated by Django 2.2 on 2020-12-01 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requesioncompra',
            old_name='id_articulo',
            new_name='articulos',
        ),
    ]
