# Generated by Django 2.2 on 2020-12-06 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0003_auto_20201205_2121'),
        ('compras', '0002_requesioncompra_comprahecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordencompra',
            name='id_oferta',
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='id_oferta',
            field=models.ManyToManyField(to='articulos.Oferta'),
        ),
    ]
