# Generated by Django 2.2 on 2020-12-06 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0003_auto_20201205_2215'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordencompra',
            old_name='id_oferta',
            new_name='ofertas',
        ),
    ]
