# Generated by Django 2.2 on 2020-11-30 23:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Depa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreDepartamento', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'Depa',
                'verbose_name_plural': 'Depas',
                'db_table': 'Depa',
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
                'db_table': 'Departamento',
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreMunicipio', models.CharField(max_length=250)),
                ('departamento_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personas.Depa')),
            ],
            options={
                'verbose_name': 'Municipio',
                'verbose_name_plural': 'Municipios',
                'db_table': 'Municipio',
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='EmpresaProvedora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25)),
                ('telefono', models.CharField(max_length=25)),
                ('direccion', models.TextField()),
                ('auth_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('depa_id', models.ForeignKey(db_column='id_depa', default=0, on_delete=django.db.models.deletion.CASCADE, to='personas.Depa')),
                ('municipio_id', models.ForeignKey(db_column='id_municipio', default=0, on_delete=django.db.models.deletion.CASCADE, to='personas.Municipio')),
            ],
            options={
                'verbose_name': 'Empresa Provedora',
                'verbose_name_plural': 'Empresa Proveedora',
                'db_table': 'Empresa Proveedora',
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primer_nombre', models.CharField(max_length=50)),
                ('segundo_nombre', models.CharField(max_length=50)),
                ('primer_apellido', models.CharField(max_length=50)),
                ('segundo_apellido', models.CharField(max_length=50)),
                ('genero', models.CharField(max_length=25)),
                ('fecha_nacimiento', models.DateField()),
                ('fecha_contratacion', models.DateField()),
                ('direccion', models.TextField()),
                ('dui', models.CharField(max_length=9)),
                ('nit', models.CharField(max_length=16)),
                ('telefono', models.CharField(max_length=25)),
                ('auth_id', models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('depa_id', models.ForeignKey(db_column='id_depa', default=0, on_delete=django.db.models.deletion.CASCADE, to='personas.Depa')),
                ('id_departamento', models.ForeignKey(db_column='id_departamento', on_delete=django.db.models.deletion.CASCADE, to='personas.Departamento')),
                ('municipio_id', models.ForeignKey(db_column='id_municipio', default=0, on_delete=django.db.models.deletion.CASCADE, to='personas.Municipio')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'db_table': 'Empleado',
                'default_permissions': [],
            },
        ),
    ]
