# Generated by Django 2.2 on 2020-12-10 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0003_auto_20201209_0003'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empleado',
            options={'permissions': [('usuarios_control', 'Manejo de los usuarios'), ('permisos_control', 'Manejo de los permisos'), ('permiso_requisicion', 'Crear Requisiciones'), ('pemisos_autorizar', 'Autorizar Requisiones'), ('permiso_articulo', 'Gestionar articulos'), ('permisos_compra', 'Gestionar orden de compra'), ('permiso_inventario', 'Gestionar inventario'), ('permiso_reportes', 'Gestionar reportes')], 'verbose_name': 'Empleado', 'verbose_name_plural': 'Empleados'},
        ),
        migrations.AlterModelOptions(
            name='empresaprovedora',
            options={'permissions': [('permisos_ofertas', 'Gestionar oferta')], 'verbose_name': 'Empresa Provedora', 'verbose_name_plural': 'Empresa Proveedora'},
        ),
    ]
