# Generated by Django 2.2 on 2020-12-10 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0004_auto_20201209_1935'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empleado',
            options={'permissions': [('usuarios_control', 'Manejo de los usuarios'), ('permisos_control', 'Manejo de los permisos'), ('permisos_requisicion', 'Crear Requisiciones'), ('pemisoss_autorizar', 'Autorizar Requisiones'), ('permisos_articulo', 'Gestionar articulos'), ('permisos_oferta', 'Gestionar oferta'), ('permisos_compra', 'Gestionar orden de compra'), ('permisos_inventario', 'Gestionar inventario'), ('permisos_reportes', 'Gestionar reportes')], 'verbose_name': 'Empleado', 'verbose_name_plural': 'Empleados'},
        ),
    ]
